import type { Metadata } from 'next'

import { cn } from '@/lib/utils'
import { INTER, IBM_PLEX_MONO } from '@/lib/font'
import { RThemeProvider, JWTProvider } from '@/components/providers'
import { TailwindIndicator } from '@/components/tailwind-indicator'

import './globals.css'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <JWTProvider>
            <html lang='en' suppressHydrationWarning>
                <body className={cn(INTER.className, IBM_PLEX_MONO.variable)}>
                    <TailwindIndicator />
                    <RThemeProvider>{children}</RThemeProvider>
                </body>
            </html>
        </JWTProvider>
    )
}
